
export const cuentas = [
  {
    _id: "68f27",
    isActive: true,
    picture: "",
    balance: "$25223",
    client: "Jose Arcadio",
    gender: "Male",
  },
  {
    _id: "68f28",
    isActive: false,
    picture: "",
    balance: "$1500",
    client: "Aureliano Buendía",
    gender: "male",
  },
  {
    _id: "68f29",
    isActive: true,
    picture: "",
    balance: "$10200",
    client: " Ursula Iguarán ",
    gender: "female",
  },
  {
    _id: "68f30",
    isActive: true,
    picture: "",
    balance: "$300",
    client: "Gerineldo Márquez",
    gender: "male",
  },
  {
    _id: "68f31",
    isActive: true,
    picture: "",
    balance: "$50000",
    client: "Mauricio Babilonia",
    gender: "male",
  },
  {
    _id: "68f32",
    isActive: true,
    picture: "",
    balance: "$12000",
    client: "Amaranta Buendía",
    gender: "female",
  },
  {
    _id: "68f33",
    isActive: false,
    picture: "",
    balance: "$500",
    client: "Rebeca Montiel",
    gender: "female",
  },
];